### ISSUE TITLE
Color Input bug?

### ISSUE THREAD

**Issue by elalemanyo** [kkga/spacegray#137]
Hi,

I have a strange color bug: http://screencast.com/t/qxsZSbzRu

Can someone help me with that?

Thanks!

**Comment by sebastienbarre** [comment]
Ugh, same here. Did you ever solve it?

**Comment by elalemanyo** [comment]
No, I didn't solve it... I am getting used to it. You?

**Comment by sebastienbarre** [comment]
I did yes, though it is likely you are using a fork of spacegray. I'm using kurtextrem/spacegray, and this color input issue comes from [a missing file](https://github.com/kurtextrem/spacegray/commit/70cd5aa0bf7d35689280ad1ed479a27f9637ec93#commitcomment-11664384). I suspect this happened when some features from the Soda theme were added in. Anyway, you can download this file (`text-field.png`) manually from many [other themes](https://github.com/search?utf8=%E2%9C%93&q=text-field+extension%3Asublime-theme&type=Code&ref=advsearch&l=) or you can comment out the line that is referencing it.

**Comment by elalemanyo** [comment]
Nice, that works! Which is the best text-field.png for spacegray theme?

Thanks

**Comment by sebastienbarre** [comment]
None of them really worked for me, because I'm using the Oceanic Next color theme, not the default Spacegreat Ocean Dark theme. So I ended up removing the reference.
```
        "class": "text_line_control",
        "layer0.texture": "",
        "layer0.opacity": 0.1,
        "content_margin": [3, 3, -1, 3],
        "layer0.inner_margin": [4, 5, 4, 3],
```

**Comment by elalemanyo** [comment]
Not sure were I should remove the reference... you are using this: https://github.com/voronianski/oceanic-next-color-scheme?

**Comment by sebastienbarre** [comment]
Yes, that color scheme, which can be used with Spacegray theme derivatives, like this [Release 3](https://github.com/kurtextrem/spacegray/releases) of a fork that has nice icons. You need to uninstall Spacegray if you installed it with Package Control, then download the ZIP file instead, install it manually, locate `Spacegray.sublime-theme`, and look for `text_line_control` in there. I would try to make it work before installing Ocean Next on top of it.

**Comment by marcofugaro** [comment]
This is relevant to a fork, which I solved in my fork of the fork, now at pull-request #176
