### ISSUE TITLE
Request: Option to disable line highlighting in the gutter.

### ISSUE THREAD

**Issue by BorisVerk** [kkga/spacegray#139]
![screen shot 2014-11-27 at 5 25 57 pm](https://cloud.githubusercontent.com/assets/5687998/5222632/dcfd9dee-765a-11e4-846f-89ee30091249.png)

I don't use line numbers or line highlighting so the light gutter current line highlight really sticks out. While I can manually edit the theme to remove this small highlight, I would really appreciate it if I only had to do it by adding an option to Settings. Is this something that can be done? Thanks for the awesome theme by the way.

**Comment by marcofugaro** [comment]
Sorry, Sublime doesn't let you do that.

If you really want remove it you can just set the color of the highlight line as the background on your machine.
http://stackoverflow.com/questions/10489546/sublime-text-2-highlight-gutter
