### ISSUE TITLE
Change sidebar font 

### ISSUE THREAD

**Issue by Zianwar** [kkga/spacegray#142]
Hi, how can I change the font of the sidebar elements?

**Comment by toph-allen** [comment]
The default for OS X *should* probably be changed to Helvetica Neue, to match Yosemite.

**Comment by marcofugaro** [comment]
[Here is the line](https://github.com/kkga/spacegray/blob/master/Spacegray.sublime-theme#L514), and [here is how](http://superuser.com/questions/748381/sublime-text-3-sidebar-font-face-change).
