### ISSUE TITLE
Atom editor support

### ISSUE THREAD

**Issue by vswamy** [kkga/spacegray#147]
Hi

Do you have plans to support this theme for Atom text editor?

--
Swamy

**Comment by iamryandrake** [comment]
I would also love to see this theme supported on Atom!

**Comment by miralize** [comment]
+1 I would love to make the switch to Atom but I love my Spacegray too much!

**Comment by itsryandrake** [comment]
I just found the port here: https://atom.io/themes/spacegray-dark-ui

Welcome to Atom buddy!

**Comment by marcofugaro** [comment]
All good, closing
