### ISSUE TITLE
Unrecognised CSS properties unreadable when using Sass

### ISSUE THREAD

**Issue by purplespider** [kkga/spacegray#149]
When using the [Sass](https://packagecontrol.io/packages/Sass) addon in ST3 with this theme, unrecognised CSS properties lose their background highlight colour when on the current line making them almost impossible to read.

Example:
![](http://spdr.me/1lFWo+)

Moving to a different line:
![](http://spdr.me/19qII+)

**Comment by marcofugaro** [comment]
fixed
