### ISSUE TITLE
Any way to make a Spacegray Terminal profile for Mac?

### ISSUE THREAD

**Issue by emilesilvis** [kkga/spacegray#151]
That would be awesome :smile:

**Comment by karelvuong** [comment]
Hey @emilesilvis, here is one that I use personally: https://github.com/karelvuong/config/blob/master/terminal/Karel.terminal.

Just download it and import into your Terminal profile list. :smile:

**Comment by emilesilvis** [comment]
@karelvuong very nice indeed! Thanks! :smile:
