### ISSUE TITLE
Highlight url in the markdown image tag

### ISSUE THREAD

**Issue by ntwcklng** [kkga/spacegray#159]
It would be nice if the url in a markdown image tag is highlighted like the url in a normal link. Maybe a bit darker/lighter?

![markdown syntax highlighting](https://cloud.githubusercontent.com/assets/8714775/7709389/02f78732-fe5d-11e4-9524-a87ec722c5d8.jpg)

What do you guys think?

**Comment by rslnk** [comment]
Agree, this way it's more readable, especially inside a text block.

**Comment by HoBi** [comment]
:+1:

**Comment by marcofugaro** [comment]
Nice catch! Fixed, out in next release
