### ISSUE TITLE
Compatibility with file type icons

### ISSUE THREAD

**Issue by plguidez** [kkga/spacegray#160]
![screen shot 2015-05-21 at 9 51 21 pm](https://cloud.githubusercontent.com/assets/6655696/7762599/538d3c2e-0005-11e5-82e4-67056a2c8030.png)

> With file type icons

![screen shot 2015-05-21 at 9 51 21 pm 2](https://cloud.githubusercontent.com/assets/6655696/7762600/5699338c-0005-11e5-825e-bd8aa954a66e.png)

> Screenshot edited for indentation to make sense hierarchically

Keep folder icons hidden, and un-hide & indent files to make sense with icons ?

**Comment by marcofugaro** [comment]
fixed in #185
