### ISSUE TITLE
Sass at-root shorthand

### ISSUE THREAD

**Issue by martindrzka** [kkga/spacegray#164]
Hi, everytime i use shorthand at-root syntax, name of selector become unreadable… Any idea?
![spacegray-sass](https://cloud.githubusercontent.com/assets/1623988/8273186/1580e604-1862-11e5-9886-25238eb2a784.gif)

**Comment by philipbordallo** [comment]
@martindrzka What Sass sublime package are you using?

It seems like it's adding an `invalid` scope to the at-root shorthand and that's why you are seeing the dark text/red selection.

**Comment by marcofugaro** [comment]
fixed
