### ISSUE TITLE
Very slow performance on Debian 8 Jessie

### ISSUE THREAD

**Issue by wadmiraal** [kkga/spacegray#166]
Hi.

Thanks for a great theme. I've tried many different ones, but I always come back to this one. I love it.

I upgraded my desktop to Debian Jessie lately. Ever since, I could not open 2 Sublime projects without noticing a *huge* drop in performance in the 2nd Sublime window (regardless of the project, small or large).

Meaning, the first Sublime window would behave normally. If I open another project, the 2nd one would be *very* slow. Even if I close the 1st project, the 2nd one will continue to be very slow, although it is the only Sublime window left open. If I close it, and re-open it, performance will be normal again.

By slow I mean incredible lag in scrolling, very slow to search (Ctrl+F), very slow typing, etc.

After disabling and completely removing many packages and not noticing any difference, I finally resorted to disable the Spacegray theme. And the lag stopped. I can now open many projects (I usually have 3 or 4 open at the same time), and performance is snappy.

I use Sublime Text 3 (build 3083, but confirmed with dev build 3095 as well).
I use Spacegray 1.2.0 (installed via the Package manager).

Any thoughts?

These are my settings, if ever:

```json
{
  "added_words":
  [
    "php"
  ],
  "bold_folder_labels": true,
  "caret_style": "phase",
  "color_scheme": "Packages/User/SublimeLinter/base16-ocean.dark (SL).tmTheme",
  "dictionary": "Packages/Language - English/en_US.dic",
  "font_face": "Fira Mono",
  "font_size": 12,
  "ignored_packages":
  [
    "DoxyDoxygen",
    "Vintage",
    "Markdown"
  ],
  "line_padding_bottom": 1,
  "line_padding_top": 1,
  "rulers":
  [
    80
  ],
  "spacegray_sidebar_font_small": true,
  "spacegray_tabs_auto_width": true,
  "spacegray_tabs_font_small": true,
  "spacegray_tabs_large": true,
  "spell_check": true,
  "tab_height": 25,
  "tab_size": 2,
  "tabs_medium": true,
  "theme": "Spacegray.sublime-theme",
  "translate_tabs_to_spaces": true,
  "trim_automatic_white_space": true,
  "trim_trailing_white_space_on_save": true,
  "word_separators": "./\\()\"'-:,.;<>~!@#%^&*|+=[]{}`~?",
  "word_wrap": true
}
```

**Comment by wadmiraal** [comment]
Ok, let me add some more information. Even with the stock Sublime 3 theme, I get the same slowdowns when too many projects are opened. So it may not specifically be tied to Spacegray, but it does get worse when Spacegray is enabled.

**Comment by gaearon** [comment]
I don't think theme developers can do anything here. You should probably file a bug with Sublime.

**Comment by wadmiraal** [comment]
I'm on it. I was only searching the ST support forum, but didn't know there are also bugs filed on Github. I am not the only one with this issue; it's indeed not theme related.

Sorry for the pollution.

**Comment by wadmiraal** [comment]
FYI, more info here: https://github.com/SublimeTextIssues/Core/issues/803
