### ISSUE TITLE
sidebar background is white

### ISSUE THREAD

**Issue by lawlietfans** [kkga/spacegray#174]
hi, i love this theme ,but when i successful install and chose spacegray theme, the sidebar background is white,  **its so ugly!**. as follows:

![shit](https://cloud.githubusercontent.com/assets/8612867/12005525/cacb9354-abe4-11e5-8167-cb0dc4a8fcf1.png)

how to solve it?  
thanks.

**Comment by marcofugaro** [comment]
It's a sublime problem I think, if it doesn't fix when you close and reopen sublime, you have to reinstall sublime, that's how I fixed it :/

**Comment by lawlietfans** [comment]
Thanks for  your advice. 
I download SyncedSidebarBg by package control. this plugin auto synchronous sidebar background color. and it works.

**Comment by SilentGene** [comment]
I also had met the problem like yours after I install the theme, and I just restart the sublime, and it worked now!

**Comment by marcofugaro** [comment]
Closing as it's a sublime problem, and restarting sublime fixes it
