### ISSUE TITLE
Height of find and replace too short

### ISSUE THREAD

**Issue by ntassone** [kkga/spacegray#177]
The height of my Find and Replace panel cuts off the Replace field:

![image](https://cloud.githubusercontent.com/assets/1572205/12703761/fb1d9110-c818-11e5-802d-175a885fc6d4.png)

**Comment by wavebeem** [comment]
Double click the top of the find and replace window and it will resize itself. I think this is a Sublime Text bug.

**Comment by scott-joe** [comment]
I installed fresh on a new mac and a new linux box and it works fine in both of those installs but no matter what I tried, the install on a slightly older MBP wouldn't fix that.

**Comment by marcofugaro** [comment]
It's a Sublime Text issue, probably with old macbooks, closing since it's not relevant to the theme.
