### ISSUE TITLE
Add panel button from Build 3101

### ISSUE THREAD

**Issue by jrappen** [kkga/spacegray#178]
> Dev Build 3101 is out now at https://www.sublimetext.com/3dev
> There's now a button on the status bar to switch between panels. If you have a custom theme, the relevant class name is panel_button_control.
> Also changed is the way Sublime Text detects changes to open files. Sublime Text 2 would simply poll the current file whenever it was switched to. This has the disadvantage that any changes to the underlying file wouldn't be noticed until either the main window itself loses and then regains input focus, or the active file was changed to something else and then back. In practice, this was only an issue if there was a 3rd party changing the file behind the scenes. It also wouldn't notice background modifications to files that are never switched to.
> Sublime Text 3 by and large worked around the missed notification issue by subscribing to file system change notifications, so that it didn't need to poll. To work around file systems that don't publish change notifications, it still polls files when an application window goes from an unfocused to a focused state, but not when simply switching between files. 3101 will now poll the active file when the active file changes, to better handle file systems that don't send change notifications.

**Comment by marcofugaro** [comment]
Here is the icon, it looks fine
![Panel Button Icon](http://i.imgur.com/URLb7Fh.png)
