### ISSUE TITLE
the underline for curly bracket is too thin

### ISSUE THREAD

**Issue by dotku** [kkga/spacegray#179]
How can I make it highlight thick underline?!
Or make it bold text?!

![image](http://i.imgur.com/1ArpDnu.png)

**Comment by stefankunze** [comment]
Use a monospace font

**Comment by marcofugaro** [comment]
Sorry, Sublime doesn't let you select the underline thickness with its API, and it looks fine.

If you want a bolder underline use this plugin
https://github.com/facelessuser/BracketHighlighter
