### ISSUE TITLE
Trailling comma on last version! (@st2)

### ISSUE THREAD

**Issue by math2001** [kkga/spacegray#189]
Hi!

With the udpate, spacegray is not working anymore? I looked in console and found this:

`Trailing comma before closing bracket in C:\Users\math\AppData\Roaming\Sublime Text 2\Packages\Theme - Spacegray\Spacegray Light.sublime-theme:665:5`

Hate this? Same. So, I've made a [little plugin that removes trailing comma when you save](https://gist.github.com/math2001/f0b52d8860f6b347301b74e15c0dfcca) 

clone it into your `User` folder of sublime text, and you're done.

Matt

**Comment by marcofugaro** [comment]
Fixed in release 1.3.1
