### ISSUE TITLE
Spacegray fileicons

### ISSUE THREAD

**Issue by MarcoAPA** [kkga/spacegray#194]
Im working with Sublime Text 2 and ive Spacegray installed with the option 
  	"spacegray_fileicons": true,
in the sublime config archive but i cant see the file icons. Am i doing something wrong with the installation? ive installed the theme via package manager and i suppose its the last version 1.3.1
![capture](https://cloud.githubusercontent.com/assets/23654184/20830722/2824cab6-b882-11e6-8ce6-3d494b9a8fcb.PNG)

**Comment by marcofugaro** [comment]
Sorry, ST2 doesn't have fileicons, so they work only in ST3

[Added a note in the README](https://github.com/kkga/spacegray/blob/master/README.md#enable-sidebar-fileicons-only-works-in-sublime-text-3)
