### ISSUE TITLE
sidebar and tabs settings appear to no longer function correctly

### ISSUE THREAD

**Issue by JohnKacz** [kkga/spacegray#197]
I have the following in my user settings and ST3 Build 3128 no longer seems to recognize or respond to them. Specifically there font side and spacing are not small.

	"spacegray_sidebar_font_small": true,
	"spacegray_sidebar_tree_xsmall": true,
	"spacegray_tabs_auto_width": true,
	"spacegray_tabs_font_small": true,
	"spacegray_tabs_small": true,

macOS 10.12.4

**Comment by stefan-o** [comment]
+1

**Comment by axsuul** [comment]
Also the font-size seems larger than usual

**Comment by thyforhtian** [comment]
I believe those were introduced with the implemeneted UI changes on ST3 side, e.g. the UI font change.

**Comment by JohnKacz** [comment]
@thyforhtian, right. I figured all the UI theme changes were the cause. I'm just not sure if the API changed (requiring a patch to spacegray) or if it's a bug in the latest build.

Note: I also just updated to 3129 and the issue is still there.

**Comment by Juje** [comment]
I tried fixing this issue by editing the `Spacegray.sublime-theme` file. And I came to notice that the following option doesn't work anymore or probably got changed:

```
"settings": ["spacegray_tabs_font_normal"],
```

So only the last option works which is the biggest option of them all.

So if you want to change the font size you have to manually edit the file do this at this moment until it's fixed.

**Comment by donileo** [comment]
Same here..

**Comment by stefan-o** [comment]
3129 has resolved my issue

**Comment by axsuul** [comment]
3129 has not fixed it for me

**Comment by szastupov** [comment]
3131 fixed it for me

**Comment by JohnKacz** [comment]
Same here. I think this can be closed now.

**Comment by marcofugaro** [comment]
Alright.
