### ISSUE TITLE
Missing sidebar icons and folder chevrons

### ISSUE THREAD

**Issue by kbjr** [kkga/spacegray#199]
On Windows 10.

Just updated to 3129, and now I cannot get icons or the open/close folder chevrons to show in the sidebar. They are there if I switch to the default theme, just don't seem to work with Spacegray. I tried uninstalling and reinstalling Spacegray with no effect.

![capture 8](https://cloud.githubusercontent.com/assets/195127/25068597/7b2a8bce-221d-11e7-94d7-e72a3251e133.png)

**Comment by thyforhtian** [comment]
Start reading recently opened issues. 
https://github.com/kkga/spacegray/issues/197

All of the sidebar issues are fixed with Sublime Text 3131.

**Comment by kbjr** [comment]
Yep, confirmed, my issue is fixed in 3131.
