### ISSUE TITLE
Custom Title Bar Mac

### ISSUE THREAD

**Issue by Superpencil** [kkga/spacegray#202]
This is available on the new Sublime builds
https://www.sublimetext.com/docs/3/themes.html#elements-windows

**Comment by MartinAyla** [comment]
I hope this will be added :)

**Comment by systo** [comment]
Gets my vote as well 👍

**Comment by superzazu** [comment]
For those interested, I already made a commit [on my fork](https://github.com/superzazu/spacegray/commit/18c4e0d2d2eefd66330c568b7149e96174e12099) for that.

I wonder if I should open a MR ? There's already #198 but this MR only adds custom title bar for `Spacegray Eighties.sublime-theme`.

**Comment by Cottin** [comment]
Just a small tip until this is merged:
I found a theme called "Adaptive" which seems to adapt the title bar to the color-scheme you choose. This was "good enough" for me. I'm at build 3134 and "Adaptive" seems included by default:

![adaptive_sublime](https://user-images.githubusercontent.com/4736419/33826232-8fc01334-de64-11e7-8c66-f3666b8e275d.jpg)

**Comment by marcofugaro** [comment]
It is now integrated, relative commit is 344d8f6

**Comment by gaearon** [comment]
Sweeeet, I love it!
