### ISSUE TITLE
Sidebar close / non-saved file indicators misaligned

### ISSUE THREAD

**Issue by aymgal** [kkga/spacegray#205]
Hi,

I don't remind exactly the moment when this issue appeared, but I noticed a misalignment of the cross or circle indicator in the sidebar :
![capture d ecran 2017-11-23 a 16 16 35](https://user-images.githubusercontent.com/10706063/33179542-116781c8-d06a-11e7-9fd8-2df6fbe2de0f.jpg)

Same issue with in every Spacegray themes or colour schemes, and does not depend on the fact that a project or a single file is open.
I'm on the latest versions of ST 3 (build 3143) and Spacegray, on macOS Sierra 10.12.6.

EDIT : the issue disappears when I toggle off the file icons, if this can help to understand. This is independent on the font size.

**Comment by bomis** [comment]
I'm seeing the same issue on linux.

**Comment by droptable** [comment]
Workaround:

Open Spacegrey.sublime-theme (e.g. using Resource Viewer)
Search for `"class": "sidebar_tree"`
In this section replace `"indent_top_level": false,"` to `"indent_top_level": true,"`

**Comment by aymgal** [comment]
Works perfectly, thanks.
