### ISSUE TITLE
Tabs won't work anymore.

### ISSUE THREAD

**Issue by berkaey** [kkga/spacegray#206]
Hey there, after last update on Sublime, tabs won't work anymore (macOS). The window merge section on "Window" also disappeared.

PS: I meant native macOS tabs.

**Comment by marcofugaro** [comment]
Hey, can you provide a screenshot and be more specific about how to reproduce the issue? Can't understand what you're referring to.

**Comment by berkaey** [comment]
![screen shot 2017-12-26 at 16 08 06](https://user-images.githubusercontent.com/4539951/34357302-ff66a178-ea56-11e7-93d3-b25a4d14c9d5.png)
<img width="721" alt="screen shot 2017-12-26 at 16 07 42" src="https://user-images.githubusercontent.com/4539951/34357303-ff8e02fe-ea56-11e7-950b-c72e6b84ce5a.png">
<img width="721" alt="screen shot 2017-12-26 at 16 04 52" src="https://user-images.githubusercontent.com/4539951/34357304-ffafc42a-ea56-11e7-986a-feb2456bc114.png">

here we go, as you can see on boxy theme I can use native macOS tabs but when I switched to space gray tabs got weird + after reset the sublime I can't event merge windows (as tabs).

**Comment by jeffersonmartin** [comment]
This feature broke for me as well. If I switched off of using the Spacegray theme it does work. At first I thought it was a High Sierra bug. 

If possible, I would suggest adding it as a bullet on the package control version release messages that it breaks full screen tab support.

```
  New in Spacegray 1.3.3:
  
    - Add support for custom Title Bar in OSX
    - Breaks support for full screen project tabs in OSX
  
```

**Comment by marcofugaro** [comment]
Well apparently after some research it turns out that

> Colored title bars disable macOS Sierra tabs.

I've added the possibility to switch off the custom title bar for you guys, put this line in your sublime Preferences:

```json
    "disable_custom_title_bar": true,
```
