### ISSUE TITLE
I'm unable to get Icons to appear in File tree ST3, WIN10

### ISSUE THREAD

**Issue by BeyondAntares** [kkga/spacegray#207]
I have windows 10 Build v17046 and ST3
I'm unable to get file icons to appear. Could someone tell me what settings I may have entered wrongly?
Here is my user settings and a screen shot of my environment:

```
{
	
	"color_scheme": "Packages/Theme - Spacegray/base16-ocean.dark.tmTheme",
	"theme": "Spacegray.sublime-theme",
	"spacegray_tabs_font_large": true,
	"font_face": "Source Code Pro",
	"font_size": 10,
	"spacegray_sidebar_font_large": true,
	"spacegray_tabs_font_normal": true,
	"spacegray_tabs_large": true,
	"spacegray_sidebar_tree_large": true,
	"spacegray_tabs_auto_width": true,
	"spacegray_sidebar_tree_large": true,
	"spacegray_fileicons": true,
	"spacegray_sidebar_font_large": true,
	
}
```
![capture](https://user-images.githubusercontent.com/28851743/34580131-ee417c48-f1df-11e7-9b82-aa4e1a3e5c42.PNG)

**Comment by marcofugaro** [comment]
You need to add a folder to your Sublime Project, the open files section is not supported.

You can add a folder with `File` > `Open Folder`, or with `Project` > `Add Folder to Project`

**Comment by marcofugaro** [comment]
Closing
