### ISSUE TITLE
Icons issue

### ISSUE THREAD

**Issue by baptistebriel** [kkga/spacegray#215]
Hey there,

Since a few weeks icons in the sidebar and at the bottom of the screen just aren't working anymore. Do you have an idea?

Thanks!

<img width="219" alt="Screen Shot 2019-03-26 at 3 19 15 PM" src="https://user-images.githubusercontent.com/2464663/55004517-a880f800-4fda-11e9-8e98-0a4a58f2e1dc.png">
<img width="190" alt="Screen Shot 2019-03-26 at 3 19 31 PM" src="https://user-images.githubusercontent.com/2464663/55004520-aae35200-4fda-11e9-8c45-2df3e34c8b08.png">

**Comment by marcofugaro** [comment]
@baptistebriel does the problem persist if you do a fresh sublime install?

**Comment by baptistebriel** [comment]
Updating to latest release of Sublime did fixed it! Thank you.
