### ISSUE TITLE
Should the sidebar color be modified by the Theme?

### ISSUE THREAD

**Issue by kurtismullins** [kkga/spacegray#5]
I'm comparing my Sublime Text appearance with the one you have shown in your screenshot in the `README.md` file.

My side-bar is still the typical Sublime Text gray. Should this have been changed by installing your theme?

I've included a screenshot for comparison purposes. It shows your screenshot next to my running instance of Sublime Text 3.

![screen shot 2013-12-24 at 3 32 56 am](https://f.cloud.github.com/assets/1145691/1805188/3bf69700-6c76-11e3-95bf-d3729a095e31.png)

**Comment by bhanuvrat** [comment]
+1
missed the directive to add it to user_preferences and landed here.
