### ISSUE TITLE
Spacegray for Chrome Dev Tools

### ISSUE THREAD

**Issue by nickdima** [kkga/spacegray#76]
Just trowing this out there. I think it would be a great match to have an implementation of the spacegray theme also in chrome dev tools. The flat look + the base16 color schemes.

**Comment by Dogfalo** [comment]
Using the new method of creating themes with a Chrome Extension, I released a SpaceGray theme for DevTools. [Link Here](https://chrome.google.com/webstore/detail/devtools-theme-spacegray/fhncmkmacplfbillpaockoaccojlbbfg)

**Comment by kamek-pf** [comment]
Theme is broken under Chromium 45, too bad :(

**Comment by Dogfalo** [comment]
Yea I have to take some time to look into it later
